-- 0071: allow capability-gated TR-143 throughput diagnostic jobs.
ALTER TABLE jobs DROP CONSTRAINT jobs_type_check;
ALTER TABLE jobs ADD CONSTRAINT jobs_type_check CHECK (type IN (
  'SET_PARAMETER','GET_PARAMETER','CONNECTION_REQUEST','FIRMWARE_DOWNLOAD',
  'DIAGNOSTICS_PING','DIAGNOSTICS_TRACEROUTE','DIAGNOSTICS_DOWNLOAD',
  'DIAGNOSTICS_UPLOAD','ADD_OBJECT','DELETE_OBJECT','REBOOT','FACTORY_RESET',
  'SCHEDULE_INFORM','SET_PARAMETER_ATTRIBUTES','GET_PARAMETER_ATTRIBUTES',
  'UPLOAD','PARAMETER_DISCOVERY'
));
