package objstore

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
)

// Local is the on-disk backend: one file per object under root, named
// by id. Fine for a single host; use S3 for more than one replica.
type Local struct {
	root string
}

func NewLocal(root string) (*Local, error) {
	if err := os.MkdirAll(root, 0o755); err != nil {
		return nil, fmt.Errorf("create object storage root: %w", err)
	}
	return &Local{root: root}, nil
}

func (s *Local) path(id string) string {
	// filepath.Base defends against an id that tries to escape root; ids
	// are UUIDs generated by this codebase, so this is belt-and-braces.
	return filepath.Join(s.root, filepath.Base(id)+".bin")
}

func (s *Local) Save(id string, r io.Reader) (string, int64, error) {
	path := s.path(id)
	f, err := os.Create(path)
	if err != nil {
		return "", 0, fmt.Errorf("create object file: %w", err)
	}
	defer f.Close()
	hr := newHashReader(r)
	if _, err := io.Copy(f, hr); err != nil {
		os.Remove(path)
		return "", 0, fmt.Errorf("write object file: %w", err)
	}
	return hr.sum(), hr.size, nil
}

func (s *Local) Open(id string) (io.ReadSeekCloser, error) {
	f, err := os.Open(s.path(id))
	if err != nil {
		return nil, fmt.Errorf("open object file: %w", err)
	}
	return f, nil
}

func (s *Local) Remove(id string) {
	os.Remove(s.path(id))
}
