import { useEffect, useState } from "react";
import { api } from "../api/client";
import type { AlertIncident, AlertPolicy } from "../api/types";

export function Alerting() {
  const [policies,setPolicies]=useState<AlertPolicy[]>([]); const [incidents,setIncidents]=useState<AlertIncident[]>([]); const [error,setError]=useState("");
  const [name,setName]=useState(""); const [scope,setScope]=useState<AlertPolicy["scope"]>("fleet"); const [target,setTarget]=useState(""); const [priority,setPriority]=useState("P2"); const [offline,setOffline]=useState("900");
  const load=async()=>{try{const [p,i]=await Promise.all([api.listAlertPolicies(),api.listAlertIncidents("open")]);setPolicies(p.items);setIncidents(i.items);setError("")}catch{setError("Failed to load alerting data")}};
  useEffect(()=>{void load()},[]);
  const acknowledge=async(id:string)=>{await api.updateAlertIncident(id,"acknowledged");await load()};
  const create=async(e:React.FormEvent)=>{e.preventDefault();try{await api.createAlertPolicy({name,scope,...(scope==="fleet"?{}:scope==="device"?{device_id:target}:scope==="group"?{group_id:target}:{tenant_id:target}),fault_priorities:{offline:priority},offline_after:Number(offline)*1e9,steps:[]});setName("");setTarget("");await load()}catch{setError("Failed to create alert policy")}};
  return <section><div className="page-head"><div><h1>Alerting & escalation</h1><p className="dim">Policy precedence: device → group → tenant → fleet.</p></div><button className="btn" onClick={()=>void load()}>Refresh</button></div>{error&&<div className="banner error">{error}</div>}<div className="panel"><h3>Create alert policy</h3><form onSubmit={create}><div className="form-row"><label className="field"><span>Name</span><input value={name} onChange={e=>setName(e.target.value)} required/></label><label className="field"><span>Scope</span><select value={scope} onChange={e=>setScope(e.target.value as AlertPolicy["scope"])}><option value="fleet">Fleet</option><option value="tenant">Tenant</option><option value="group">Device group</option><option value="device">Individual CPE</option></select></label></div>{scope!=="fleet"&&<label className="field"><span>{scope} ID</span><input value={target} onChange={e=>setTarget(e.target.value)} required/></label>}<div className="form-row"><label className="field"><span>Offline priority</span><select value={priority} onChange={e=>setPriority(e.target.value)}><option>P1</option><option>P2</option><option>P3</option></select></label><label className="field"><span>Offline threshold (seconds)</span><input type="number" min="0" value={offline} onChange={e=>setOffline(e.target.value)} required/></label></div><button className="btn primary" type="submit" disabled={!name|| (scope!=="fleet"&&!target)}>Create policy</button></form></div><div className="panel"><h3>Active incidents</h3>{incidents.length===0?<p className="dim">No open incidents.</p>:<div className="table-wrap"><table><thead><tr><th>Priority</th><th>Tenant</th><th>Device</th><th>Summary</th><th>Stage</th><th/></tr></thead><tbody>{incidents.map(i=><tr key={i.id}><td><span className={`pill ${i.priority === "P1" ? "pill-bad" : "pill-warn"}`}>{i.priority}</span></td><td>{i.tenant_id}</td><td className="mono">{i.device_id}</td><td>{i.summary}</td><td>{i.escalation_stage}</td><td><button className="btn sm" onClick={()=>void acknowledge(i.id)}>Acknowledge</button></td></tr>)}</tbody></table></div>}</div><div className="panel"><h3>Configured policies</h3>{policies.length===0?<p className="dim">No alert policies configured.</p>:<div className="table-wrap"><table><thead><tr><th>Name</th><th>Scope</th><th>Tier</th><th>Offline threshold</th></tr></thead><tbody>{policies.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.scope}</td><td>{p.customer_tier||"—"}</td><td>{p.offline_after||"—"}</td></tr>)}</tbody></table></div>}</div></section>;
}
